In [1]:
# llibraries
import pandas as pd
import numpy as np

In [ ]:
/Users/xiashuchu/repositories/OTC_MARKETS/hhc390ihqgzwa4hy.csv

In [ ]:
# Read the CSV file in chunks
chunk_size = 500
chunks = pd.read_csv("/Users/xiashuchu/repositories/OTC_MARKETS/hhc390ihqgzwa4hy.csv", chunksize=chunk_size)

# Example: Summarize each chunk or perform any operation
for chunk in chunks:
    print(chunk.head())  # Or perform calculations

# Read specific columns
cols_to_use = ['Column1', 'Column2', 'Column3']
data_partial = pd.read_csv(file_path, usecols=cols_to_use)
print(data_partial.head())

# Skip rows and set no header
data_no_header = pd.read_csv(file_path, header=None, skiprows=10)
print(data_no_header.head())

In [2]:


# Replace 'path_to_your_file.csv' with the path to your CSV file
file_path = '/Users/xiashuchu/repositories/OTC_MARKETS/hhc390ihqgzwa4hy.csv'

# Read the first 5 rows
data = pd.read_csv(file_path, nrows=5)

# Display the data
print(data)

    SECID  CompID Symbol      CUSIP                 Issue        Venue  \
0  100010  649124  GPGPF  G4205Y111  GUINESS PEAT GRP PLC  Grey Market
1  100010  649124  GPGPF  G4205Y111  GUINESS PEAT GRP PLC  Grey Market
2  100010  649124  GPGPF  G4205Y111  GUINESS PEAT GRP PLC  Grey Market
3  100010  649124  GPGPF  G4205Y111  GUINESS PEAT GRP PLC  Grey Market
4  100010  649124  GPGPF  G4205Y111  GUINESS PEAT GRP PLC  Grey Market

           SecType  Class CaveatEmptor     TierName  ...  TierID  \
0  Ordinary Shares    NaN            N  Grey Market  ...      30
1  Ordinary Shares    NaN            N  Grey Market  ...      30
2  Ordinary Shares    NaN            N  Grey Market  ...      30
3  Ordinary Shares    NaN            N  Grey Market  ...      30
4  Ordinary Shares    NaN            N  Grey Market  ...      30

   ClosingBestBid  ClosingBestBidDate  BestBidSource  ClosingBestAsk  \
0             NaN          2011-09-01            NaN             NaN
1             NaN          2011-09-02            NaN             NaN
2             NaN          2011-09-06            NaN             NaN
3             NaN          2011-09-07            NaN             NaN
4             NaN          2011-09-08            NaN             NaN

   ClosingBestAskDate  BestAskSource  SecurityStatus  SharesOutstanding  \
0          2011-09-01            NaN          Active                NaN
1          2011-09-02            NaN          Active                NaN
2          2011-09-06            NaN          Active                NaN
3          2011-09-07            NaN          Active                NaN
4          2011-09-08            NaN          Active                NaN

   SharesOutstandingAsOfDate
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN

[5 rows x 44 columns]

In [4]:
data.shape

(5, 44)

In [5]:
# Iterate over each column in the DataFrame
for column in data.columns:
    print(f"Column: {column}")
    print(data[column])
    print("\n")  # This adds a new line for better readability between columns

Column: SECID
0    100010
1    100010
2    100010
3    100010
4    100010
Name: SECID, dtype: int64


Column: CompID
0    649124
1    649124
2    649124
3    649124
4    649124
Name: CompID, dtype: int64


Column: Symbol
0    GPGPF
1    GPGPF
2    GPGPF
3    GPGPF
4    GPGPF
Name: Symbol, dtype: object


Column: CUSIP
0    G4205Y111
1    G4205Y111
2    G4205Y111
3    G4205Y111
4    G4205Y111
Name: CUSIP, dtype: object


Column: Issue
0    GUINESS PEAT GRP PLC
1    GUINESS PEAT GRP PLC
2    GUINESS PEAT GRP PLC
3    GUINESS PEAT GRP PLC
4    GUINESS PEAT GRP PLC
Name: Issue, dtype: object


Column: Venue
0    Grey Market
1    Grey Market
2    Grey Market
3    Grey Market
4    Grey Market
Name: Venue, dtype: object


Column: SecType
0    Ordinary Shares
1    Ordinary Shares
2    Ordinary Shares
3    Ordinary Shares
4    Ordinary Shares
Name: SecType, dtype: object


Column: Class
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Class, dtype: float64


Column: CaveatEmptor
0    N
1    N
2    N
3    N
4    N
Name: CaveatEmptor, dtype: object


Column: TierName
0    Grey Market
1    Grey Market
2    Grey Market
3    Grey Market
4    Grey Market
Name: TierName, dtype: object


Column: DAD_PAL
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: DAD_PAL, dtype: float64


Column: ClosingInsideBidPrice
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: ClosingInsideBidPrice, dtype: float64


Column: ClosingInsideBidPriceDate
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: ClosingInsideBidPriceDate, dtype: float64


Column: ClosingInsideAskPrice
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: ClosingInsideAskPrice, dtype: float64


Column: ClosingInsideAskPriceDate
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: ClosingInsideAskPriceDate, dtype: float64


Column: InsideBid_AskMidPrice
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: InsideBid_AskMidPrice, dtype: float64


Column: OpenPrice
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: OpenPrice, dtype: float64


Column: HighPrice
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: HighPrice, dtype: float64


Column: LowPrice
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: LowPrice, dtype: float64


Column: LastPrice
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: LastPrice, dtype: float64


Column: PreviousClosePrice
0    0.48
1    0.48
2    0.48
3    0.48
4    0.48
Name: PreviousClosePrice, dtype: float64


Column: PreviousCloseDate
0    2011-08-18
1    2011-08-18
2    2011-08-18
3    2011-08-18
4    2011-08-18
Name: PreviousCloseDate, dtype: object


Column: ShareVolume
0    0
1    0
2    0
3    0
4    0
Name: ShareVolume, dtype: int64


Column: DollarVol
0    0
1    0
2    0
3    0
4    0
Name: DollarVol, dtype: int64


Column: TradeCount
0    0
1    0
2    0
3    0
4    0
Name: TradeCount, dtype: int64


Column: OTCLinkDolVol
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: OTCLinkDolVol, dtype: float64


Column: OTCLinkShareVol
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: OTCLinkShareVol, dtype: float64


Column: OTCLinkExecCount
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: OTCLinkExecCount, dtype: float64


Column: SHOFlag
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: SHOFlag, dtype: float64


Column: Rule3210Flag
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Rule3210Flag, dtype: float64


Column: ShortIntVol
0    0
1    0
2    0
3    0
4    0
Name: ShortIntVol, dtype: int64


Column: ShortInterestDate
0    2011-07-15
1    2011-07-15
2    2011-07-15
3    2011-07-15
4    2011-07-15
Name: ShortInterestDate, dtype: object


Column: MMIDCount
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: MMIDCount, dtype: float64


Column: BFCMmid
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: BFCMmid, dtype: float64


Column: TierID
0    30
1    30
2    30
3    30
4    30
Name: TierID, dtype: int64


Column: ClosingBestBid
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: ClosingBestBid, dtype: float64


Column: ClosingBestBidDate
0    2011-09-01
1    2011-09-02
2    2011-09-06
3    2011-09-07
4    2011-09-08
Name: ClosingBestBidDate, dtype: object


Column: BestBidSource
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: BestBidSource, dtype: float64


Column: ClosingBestAsk
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: ClosingBestAsk, dtype: float64


Column: ClosingBestAskDate
0    2011-09-01
1    2011-09-02
2    2011-09-06
3    2011-09-07
4    2011-09-08
Name: ClosingBestAskDate, dtype: object


Column: BestAskSource
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: BestAskSource, dtype: float64


Column: SecurityStatus
0    Active
1    Active
2    Active
3    Active
4    Active
Name: SecurityStatus, dtype: object


Column: SharesOutstanding
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: SharesOutstanding, dtype: float64


Column: SharesOutstandingAsOfDate
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: SharesOutstandingAsOfDate, dtype: float64